version: '3.8'
services:
  yolo-train:
    build: .
    container_name: yolo-rocm
    privileged: true
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
      - render
    environment:
      - HSA_OVERRIDE_GFX_VERSION=10.3.0  # for RX 6900 XT (Navi 21)
    volumes:
      - ./yolov5/data:/workspace/yolov5/data
      - ./yolov5:/workspace/yolov5  # optional if editing outside container
    stdin_open: true
    tty: true
